backend:
  name: git-gateway
  branch: main

media_folder: /static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow

site_url: https://mesaoverland.com
logo_url: https://mesaoverland.com/images/logo.png

collections:
  - name: 'build'
    label: 'Build'
    folder: 'src/content/build'
    create: true
    slug: '{{name}}'
    path: '{{name}}'
    media_folder: /static/images/uploads
    public_folder: /images/uploads
    preview_path: 'builds/{{name}}'
    fields:
      - { label: 'Build Name', name: 'name', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["Pre-Build", "For Sale", "In Progress", "Deposit Received", "Pending Sale", "Sold"]
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'faq'
    label: 'FAQ'
    folder: 'src/content/faq'
    create: false
    slug: '{{title}}'
    path: '{{title}}/index'
    media_folder: /static/images/uploads
    public_folder: /images/uploads
    preview_path: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Last Updated', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Services'
    folder: 'src/content/services'
    create: false
    slug: '{{title}}'
    path: '{{title}}/index'
    media_folder: /static/images/uploads
    public_folder: /images/uploads
    preview_path: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Last Updated', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'testimonial'
    label: 'Testimonial'
    folder: 'src/content/testimonial'
    create: true
    slug: '{{title}}'
    path: '{{title}}'
    media_folder: /static/images/uploads
    public_folder: /images/uploads
    preview_path: 'testimonials/{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }