backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images

collections:
  - name: 'build'
    label: 'Build'
    folder: 'src/content/build'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Build Name', name: 'name', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
