local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: /static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow

site_url: https://mesaoverland.com
logo_url: https://mesaoverland.com/images/logo.png

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'FAQ'
        name: 'faq'
        file: 'src/content/faq/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Last Updated', name: 'date', widget: 'datetime' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Services'
        name: 'services'
        file: 'src/content/services/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Last Updated', name: 'date', widget: 'datetime' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Builds'
    name: 'build'
    folder: 'src/content/build'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Build Name', name: 'title', widget: 'string' }
      - { label: 'Active', name: 'active', widget: 'select', options: ['true', 'false'] }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["For Sale", "Sold"]
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Reviews'
    name: 'review'
    folder: 'src/content/review'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }