local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: /static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow

site_url: https://mesaoverland.com
logo_url: https://mesaoverland.com/images/logo.png

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'FAQ'
        name: 'faq'
        file: 'src/content/faq/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Last Updated', name: 'date', widget: 'datetime' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Services'
        name: 'services'
        file: 'src/content/services/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Last Updated', name: 'date', widget: 'datetime' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Financing'
        name: 'financing'
        file: 'src/content/financing/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Last Updated', name: 'date', widget: 'datetime' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Builds'
    name: 'build'
    folder: 'src/content/build'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Build Name', name: 'title', widget: 'string' }
      - { label: 'Active', name: 'active', widget: 'select', options: ['true', 'false'] }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["For Sale", "Sold"]
      - { label: 'Price', name: 'price', widget: 'number' }
      - { label: Date, name: date, widget: date }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Reviews'
    name: 'review'
    folder: 'src/content/review'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Campers
    name: campers
    files:
      - label: 'Mid Size Camper'
        name: 'midsize'
        file: 'src/content/campers/midsize.json'
        extension: json
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Photo', name: 'photo', widget: 'image' }
          - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
          - { label: 'Upfit Price', name: 'upfit_price', widget: 'number' }
          - label: Options
            name: options
            widget: list
            fields:
            - { label: Name, name: name, widget: string }
            - { label: Price, name: price, widget: number }
            - { label: Description, name: description, widget: string }