backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow

site_url: https://mesaoverland.com
logo_url: https://mesaoverland.com/images/logo.png

collections:
  - name: 'build'
    label: 'Build'
    folder: 'src/content/build'
    create: true
    slug: 'index'
    path: '{{name}}/index'
    media_folder: static/images/uploads
    public_folder: /images/uploads
    preview_path: 'build/{{name}}'
    fields:
      - { label: 'Build Name', name: 'name', widget: 'string' }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["For Sale", "In Progress", "Pre-Build", "Deposit Received", "Sold"]
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'faq'
    label: 'FAQ'
    folder: 'src/content/faq'
    create: false
    slug: 'index'
    path: '{{title}}/index'
    media_folder: static/images/uploads
    public_folder: /images/uploads
    preview_path: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Last Updated', name: 'date', widget: 'datetime' }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
