local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: /static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow

site_url: https://mesaoverland.com
logo_url: https://mesaoverland.com/images/logo.png

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/content/home/index.md'
        extension: 'md'
        fields:
          - { label: 'Tagline', name: 'tagline', widget: 'string' }
          - { label: 'Tagline Description', name: 'tagline_desc', widget: 'string'}
          - { label: 'Hero Image', name: 'hero_image', widget: 'image'}
          - { label: 'Highlighted Camper 1 Tagline', name: 'highlight_camper_1_tagline', widget: 'string'}
          - { label: 'Highlighted Camper 1 Tagline Description', name: 'highlight_camper_1_tagline_desc', widget: 'string'}
          - { label: 'Highlighted Camper 1 Button Text', name: 'highlight_camper_1_button', widget: 'string'}
          - { label: 'Highlighted Camper 1 Image', name: 'highlight_camper_1_image', widget: 'image'}
          - { label: 'Highlighted Camper 2 Tagline', name: 'highlight_camper_2_tagline', widget: 'string'}
          - { label: 'Highlighted Camper 2 Tagline Description', name: 'highlight_camper_2_tagline_desc', widget: 'string'}
          - { label: 'Highlighted Camper 2 Button Text', name: 'highlight_camper_2_button', widget: 'string'}
          - { label: 'Highlighted Camper 2 Image', name: 'highlight_camper_2_image', widget: 'image'}
          - label: Gallery
            name: gallery
            widget: list
            fields:
            - { label: Image, name: image, widget: image }
      - label: 'FAQ'
        name: 'faq'
        file: 'src/content/faq/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Services'
        name: 'services'
        file: 'src/content/services/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Financing'
        name: 'financing'
        file: 'src/content/financing/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Header Image', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About'
        name: 'about'
        file: 'src/content/about/index.md'
        extension: 'md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'About Text', name: 'body', widget: 'markdown' }
  - label: 'Builds'
    name: 'build'
    folder: 'src/content/build'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Build Name', name: 'title', widget: 'string' }
      - { label: 'Active', name: 'active', widget: 'select', options: ['true', 'false'] }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["For Sale", "Sold"]
      - { label: 'Price', name: 'price', widget: 'number' }
      - { label: Date, name: date, widget: date }
      - { label: 'Header Image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Reviews'
    name: 'review'
    folder: 'src/content/review'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Slide In Campers
    name: slideincampers
    files:
    - label: 'Mid Size Short Bed'
      name: 'slideinmidshort'
      file: 'src/content/campers/slidein/midshort.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
    - label: 'Mid Size Long Bed'
      name: 'slideinmidlong'
      file: 'src/content/campers/slidein/midlong.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
    - label: 'Full Size 5.5 Bed'
      name: 'slideinfullshort'
      file: 'src/content/campers/slidein/fullshort.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }      
    - label: 'Full Size 6.5 Bed'
      name: 'slideinfullmed'
      file: 'src/content/campers/slidein/fullmed.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
    - label: 'Full Size 8 Bed'
      name: 'slideinfulllong'
      file: 'src/content/campers/slidein/fulllong.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
  - label: Flat Bed Campers
    name: flatbedcampers
    files:
    - label: 'Mid Size Long Bed'
      name: 'flatbedmidlong'
      file: 'src/content/campers/flatbed/midlong.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
    - label: 'Full Size 6.5 Bed'
      name: 'flatbedfullmed'
      file: 'src/content/campers/flatbed/fullmed.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
    - label: 'Full Size 8 Bed'
      name: 'flatbedfulllong'
      file: 'src/content/campers/flatbed/fulllong.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
  - label: Chassis Mount Campers
    name: chassiscampers
    files:
    - label: '6.5 Bed'
      name: 'chassisshort'
      file: 'src/content/campers/chassis/short.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }
    - label: '8 Bed'
      name: 'chassislong'
      file: 'src/content/campers/chassis/long.md'
      extension: md
      fields:
        - { label: 'Name', name: 'name', widget: 'string' }
        - { label: 'Short Description', name: 'short_description', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'string' }
        - { label: 'Photo', name: 'photo', widget: 'image' }
        - { label: 'Shell Price', name: 'shell_price', widget: 'number' }
        - { label: 'Lead Time (# of weeks)', name: 'lead_time_weeks', widget: 'number' }
        - label: Features
          name: features
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
        - label: Specifications
          name: specs
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: Value, name: value, widget: string }
        - label: Options
          name: options
          widget: list
          fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Description', name: 'description', widget: 'string', required: false }
          - { label: Price, name: price, widget: number }
          - label: Category
            name: category
            widget: select
            options: ['standard', 'exterior', 'interior', 'window', 'accessory', 'color']
        - label: Gallery
          name: gallery
          widget: list
          fields:
          - { label: Image, name: image, widget: image }